name: 'MyDynamicSecret'
on: push

jobs: 
  fetch_dynamic_secrets:
    runs-on: 'ubuntu-latest'
    name: Fetch dynamic secrets
    
    permissions:
      id-token: write
      contents: read
      
    steps:
    - name: Fetch dynamic secrets from Akeyless
      id: fetch-dynamic-secrets
      uses: LanceMcCarthy/akeyless-action@v3.1.1
      with:
        access-id: ${{ secrets.ACCESS_ID }}
        dynamic-secrets: '{"awsDS":"MY_SECRET"}'
        
    - name: Export Secrets to Environment
      run: |
        echo '${{ steps.fetch-dynamic-secrets.outputs.MY_SECRET }}' | jq -r 'to_entries|map("JWT_\(.key)=\(.value|tostring)")|.[]' >> $GITHUB_ENV
# You can now access each secret separately as environment variables
    - name: Verify Vars
      run: |
        echo "access_key_id: ${{ env.JWT_access_key_id }}"
        echo "id: ${{ env.JWT_id }}"
        echo "secret_access_key: ${{ env.JWT_secret_access_key }}"
        echo "type: ${{ env.JWT_type }}"
