name: AppSecIL 2023 Test Github Actions

on: push

jobs: 
  appsecil: 
    runs-on: ubuntu-latest
    name: hello world!
    steps:
      - run: echo "hello appsecil 2023!"
      - run: id
      - run: uname -a
      - run: env
  owasp-zap:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://juice-shop.herokuapp.com/'

